services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    AmorebietakoUdala\SMSServiceBundle\Providers\SmsDinaHostingApi:
        class: AmorebietakoUdala\SMSServiceBundle\Providers\SmsDinaHostingApi
        public: true
        autowire: true
        arguments: ['%username%','%password%','%account%','%test%','%sender%']
        
    AmorebietakoUdala\SMSServiceBundle\Providers\SmsAcumbamailApi:
        class: AmorebietakoUdala\SMSServiceBundle\Providers\SmsAcumbamailApi
        public: true
        autowire: true
        arguments: ['%authToken%', '%test%', '%sender%','%version%', '%timeout%', '%countryCode%']

    AmorebietakoUdala\SMSServiceBundle\Services\SmsServiceApi:
        public: true
        autowire: true
        arguments: ['%provider%','@AmorebietakoUdala\SMSServiceBundle\Providers\SmsDinaHostingApi','@AmorebietakoUdala\SMSServiceBundle\Providers\SmsAcumbamailApi']

    AmorebietakoUdala\SMSServiceBundle\Controller\DefaultController:
        tags: ['controller.service_arguments']
        public: true
        autowire: true
